<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{6229951d-7c2a-451d-aeaf-626ebb47240f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
// PLC Methode
 HmiMapping();
 HmiFunctionAddition();
 HmiFunctionLizenz();

// Hmi Classic

// Hmi Vue3

// Testing

]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>